services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    # volumes:
    #   - ./data:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_ALIAS=redis
      - RI_REDIS_USERNAME=default
      - RI_REDIS_PASSWORD=
    depends_on:
      - redis
